<div class="row">
    <div class="col-lg-offset-2 col-md-8">
        <a href="#" class="thumbnail">
            <img data-src="holder.js/100%x400/vine/text:Intro Video" alt="...">
        </a>
    </div>
</div>

<div class="row">
    <div class="col-lg-offset-2 col-md-8">
        <img data-src="holder.js/100%x400/lava/text:Activity" alt="...">
    </div>
</div>

<div class="row" style="padding-top: 12px">
    <div class="col-lg-offset-2 col-md-8 text-right">
        <p>
            <a href="/pages/progress" class="btn btn-primary btn-lg">Next</a>
        </p>
    </div>
</div>