<div class="row">
    <div class="col-lg-offset-2 col-md-8">
        <a href="#" class="thumbnail">
            <img data-src="holder.js/100%x400/vine/text:Intro Video" alt="...">
        </a>
    </div>
</div>

<div class="row">
    <div class="col-lg-offset-2 col-md-8">
        <p>Space, the final frontier. These are the voyages of the Starship Enterprise. Its five-year mission: to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no man has gone before.</p>

        <p>For those who have seen the Earth from space, and for the hundreds and perhaps thousands more who will, the experience most certainly changes your perspective. The things that we share in our world are far more valuable than those which divide us.</p>

        <p>Across the sea of space, the stars are other suns.</p>
    </div>
</div>

<div class="row">
    <div class="col-lg-offset-2 col-md-8 text-right">
        <a href="/pages/activity" class="btn btn-primary btn-lg">Next</a>
    </div>
</div>