<div class='row'>
    <div class='col-md-12'>

            <h1>
                Terms and Conditions
            </h1>

        <p>
            Subscriptions to the mSchool service are subject to the acceptance of all terms set forth in the this agreement.
            Use of this website represents acceptance of these terms. Users attest that they are authorized to possess, distribute,
            and access all academic data entered into and accessed via the mSchool system. Payments outstanding more than
            30 days may result in cancellation of the subscriptions. All fees and payments are non- refundable. No failure
            or delay by mSchool in exercising any right shall constitute a waiver of that right. mSchool does not warrant
            its products or services except as specifically agreed to in writing. Any dispute regarding this Quote shall
            be governed by the laws of the State of Louisiana, and the parties agree to accept the exclusive jurisdiction
            of the state and federal courts located in Orleans Parish, Louisiana, regardless of conflicts of laws. All services
            re provided “as is.” mSchool disclaims all express and implied warranties. Initial Term of the Use Agreement shall
            be 1 month from the Billing Start Date as set forth in the preceding Services Agreement unless otherwise specified
            via purchase order. At the end of the initial term, regardless of length, this Agreement shall be able to be renewed
            automatically for consecutive renewal terms of 1 calendar month, unless otherwise requested by Purchaser. Termination
            shall be customer’s sole and exclusive remedy in case of non- or mal-performance by mSchool, and can be effected by
            either party’s written notice, effective upon completion of the current billing month.</p>

    </div>
</div>