<h2>Edit Pathway</h2>

<?php

$form = $this->form;
$form->prepare();

$form->setAttribute('method', 'post');

echo $this->form()->openTag($form->setAttribute('class', 'form'));
?>

<?php $element = $form->get('name'); ?>
<div class="row">
    <div class="form-group <?php echo (!$element->getMessages()) ?: ('has-error') ?>">
        <div class="col-md-4">
            <label class="control-label" for="name">Name</label>
            <?php
            echo $this->formInput($element->setAttribute('class', 'form-control')->setAttribute('placeholder', ''));
            echo $this->formElementErrors($element);
            ?>
        </div>
    </div>
</div>

<?php $element = $form->get('short_code'); ?>
<div class="row">
    <div class="form-group <?php echo (!$element->getMessages()) ?: ('has-error') ?>">
        <div class="col-md-4">
            <label class="control-label" for="short_code">Short Code</label>
            <?php
            echo $this->formInput($element->setAttribute('class', 'form-control')->setAttribute('placeholder', ''));
            echo $this->formElementErrors($element);
            ?>
        </div>
    </div>
</div>

<?php $element = $form->get('is_active'); ?>
<div class="row">
    <div class="form-group <?php echo (!$element->getMessages()) ?: ('has-error') ?>">
        <div class="col-md-4">
            <label class="control-label" for="short_code">Is Active</label>
            <?php
            echo $this->formCheckbox($element->setAttribute('class', 'form-control')->setAttribute('placeholder', ''));
            echo $this->formElementErrors($element);
            ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="form-group">
        <div class="col-md-2">
            <label class="control-label" for=""></label>
            <?php
            $submit = $form->get('submit');
            echo $this->formInput($submit ->setAttribute('class', 'btn btn-primary btn-block')->setValue('Update'));
            echo $this->formElementErrors($submit );
            ?>
        </div>
    </div>
</div>

<div class="row" style="padding-top: 12px">
    <div class="col-md-2">
        <a href="<?php echo $this->url('admin/pathways') ?>" class="btn btn-default btn-sm">Cancel</a>
    </div>
</div>

<?php echo $this->form()->closeTag() ?>

<hr />

<h3>Pathway Plans</h3>

<div class="row">
    <div class="col-md-12">
        <p>Changes to this Pathway's do not affect current assignments to students.</p>
    </div>
</div>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Name</th>
            <th>Short Code</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($pathwayPlans as $pathwayPlan): ?>
            <tr>
                <td><?php echo $pathwayPlan->plan->name ?></td>
                <td><?php echo $pathwayPlan->plan->shortCode ?></td>
                <td class="text-right">
                    <?php
                        $form = $this->removePlanForm;
                        $form->prepare();
                        $form->setPathwayPlan($pathwayPlan);
                        $form->setAttribute('method', 'post');
                        $form->setAttribute('action', $this->url('admin/pathway_remove_plan', array('id' => $pathway->id)));
                        echo $this->form()->openTag($form->setAttribute('class', 'form'));
                        echo $this->formHidden($form->get('pathwayplan_id'));
                        echo $this->formInput($removePlanForm->get('submit')->setAttribute('class', 'btn btn-danger')->setValue('Remove Plan'));
                        echo $this->form()->closeTag();
                    ?>
                </td>
            </tr>
        <?php endforeach; ?>

        <?php if (!count($pathwayPlans)): ?>
            <tr>
                <td colspan="3">
                    There are no plans associated with this pathway.
                </td>

            </tr>
        <?php endif; ?>
    </tbody>
</table>

<?php
    /* ******************************************** */
?>

<?php

$addPlanForm = $this->addPlanForm;
$addPlanForm->prepare();

$addPlanForm->setAttribute('method', 'post');

$addPlanForm->setAttribute('action', $this->url('admin/pathway_add_plan', array('id' => $pathway->id)));

echo $this->form()->openTag($addPlanForm->setAttribute('class', 'form'));
?>

<?php $element = $addPlanForm->get('plan_id'); ?>
<div class="row">
    <div class="form-group <?php echo (!$element->getMessages()) ?: ('has-error') ?>">
        <div class="col-md-4">
            <?php
            echo $this->formSelect($element->setAttribute('class', 'form-control')->setAttribute('placeholder', ''));
            echo $this->formElementErrors($element);
            ?>
        </div>

        <div class="col-md-2">
            <?php
            $submit = $addPlanForm->get('submit');
            echo $this->formInput($submit ->setAttribute('class', 'btn btn-primary btn-block')->setValue('Add Plan'));
            echo $this->formElementErrors($submit );
            ?>
        </div>
    </div>
</div>

<?php echo $this->form()->closeTag() ?>

