<h3>Pathway Upload Preview</h3>
<div class="row">
    <div class="col-md-12 text-right">
        <p><a class="btn btn-primary" href="">Confirm</a> <a class="btn btn-danger" href="">Re-upload</a></p>
    </div>
</div>

<table class="table table-striped">
    <tbody>
        <tr>
            <td>Jamie Anderson</td>
            <td>02/10/14</td>
            <td>1</td>
            <td>Daily Intro</td>
            <td>Do you best.</td>
            <td>http://someplace.co/thing/you/need</td>
        </tr>
        <tr>
            <td>Jamie Anderson</td>
            <td>02/12/14</td>
            <td>2</td>
            <td>Daily Activity</td>
            <td>You can do it!</td>
            <td>http://superfunsite.com/check/this-out.html</td>
        </tr>

        <tr>
            <td>Jamie Anderson</td>
            <td>02/14/14</td>
            <td>3</td>
            <td>Progress</td>
            <td>Good job.</td>
            <td></td>
        </tr>

        <!-- **** -->

        <tr>
            <td>Sage Kotsenburg</td>
            <td>02/10/14</td>
            <td>1</td>
            <td>Daily Intro</td>
            <td>Do you best.</td>
            <td>http://someplace.co/thing/you/need</td>
        </tr>
        <tr>
            <td>Sage Kotsenburg</td>
            <td>02/10/14</td>
            <td>2</td>
            <td>Daily Activity</td>
            <td>You can do it!</td>
            <td>http://superfunsite.com/check/this-out.html</td>
        </tr>

        <tr>
            <td>Sage Kotsenburg</td>
            <td>02/14/14</td>
            <td>3</td>
            <td>Progress</td>
            <td>Good job.</td>
            <td></td>
        </tr>

        <!-- **** -->

        <tr>
            <td>Hannah Kearney</td>
            <td>02/10/14</td>
            <td>1</td>
            <td>Daily Intro</td>
            <td>Do you best.</td>
            <td>http://someplace.co/thing/you/need</td>
        </tr>
        <tr>
            <td>Hannah Kearney</td>
            <td>02/10/14</td>
            <td>2</td>
            <td>Daily Activity</td>
            <td>You can do it!</td>
            <td>http://superfunsite.com/check/this-out.html</td>
        </tr>

        <tr>
            <td>Hannah Kearney</td>
            <td>02/14/14</td>
            <td>3</td>
            <td>Progress</td>
            <td>Good job.</td>
            <td></td>
        </tr>

        <!-- **** -->

        <tr>
            <td>Gracie Gold</td>
            <td>02/10/14</td>
            <td>1</td>
            <td>Daily Intro</td>
            <td>Do you best.</td>
            <td>http://someplace.co/thing/you/need</td>
        </tr>
        <tr>
            <td>Gracie Gold</td>
            <td>02/12/14</td>
            <td>2</td>
            <td>Daily Activity</td>
            <td>You can do it!</td>
            <td>http://superfunsite.com/check/this-out.html</td>
        </tr>

        <tr>
            <td>Gracie Gold</td>
            <td>02/14/14</td>
            <td>3</td>
            <td>Progress</td>
            <td>Good job.</td>
            <td></td>
        </tr>

        <!-- **** -->

    </tbody>

</table>

<div class="row">
    <div class="col-md-12 text-right">
        <p><a class="btn btn-primary" href="">Confirm</a> <a class="btn btn-danger" href="">Re-upload</a></p>
    </div>
</div>