<!DOCTYPE html>
<html>
<head>
    <title>mSchool Admin <?php echo ($this->pageTitle) ? (' - ' . $this->pageTitle) : (''); ?></title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <meta content='text/html;charset=utf-8' http-equiv='content-type'>
<!--    <meta content='Flat administration template for Twitter Bootstrap. Twitter Bootstrap 3 template with Ruby on Rails support.' name='description'>-->
    <link rel="icon" type="image/png" href="/assets/mschool/images/favicon.png">
<!--    <link href='/assets/images/meta_icons/favicon.ico' rel='shortcut icon' type='image/x-icon'>-->
<!--    <link href='/assets/images/meta_icons/apple-touch-icon.png' rel='apple-touch-icon-precomposed'>-->
<!--    <link href='/assets/images/meta_icons/apple-touch-icon-57x57.png' rel='apple-touch-icon-precomposed' sizes='57x57'>-->
<!--    <link href='/assets/images/meta_icons/apple-touch-icon-72x72.png' rel='apple-touch-icon-precomposed' sizes='72x72'>-->
<!--    <link href='/assets/images/meta_icons/apple-touch-icon-114x114.png' rel='apple-touch-icon-precomposed' sizes='114x114'>-->
<!--    <link href='/assets/images/meta_icons/apple-touch-icon-144x144.png' rel='apple-touch-icon-precomposed' sizes='144x144'>-->
    <!-- / START - page related stylesheets [optional] -->
    <link href="/assets/stylesheets/plugins/bootstrap_daterangepicker/bootstrap-daterangepicker.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/assets/stylesheets/plugins/fullcalendar/fullcalendar.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/assets/stylesheets/plugins/common/bootstrap-wysihtml5.css" media="all" rel="stylesheet" type="text/css" />
    <!-- / END - page related stylesheets [optional] -->
    <!-- / bootstrap [required] -->
    <link href="/assets/stylesheets/bootstrap/bootstrap.css" media="all" rel="stylesheet" type="text/css" />
    <!-- / theme file [required] -->
    <link href="/assets/stylesheets/light-theme.css" media="all" id="color-settings-body-color" rel="stylesheet" type="text/css" />
    <!-- / coloring file [optional] (if you are going to use custom contrast color) -->
    <link href="/assets/stylesheets/theme-colors.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/assets/mschool/stylesheets/mschool.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/assets/mschool/stylesheets/mschool-admin.css" media="all" rel="stylesheet" type="text/css" />
    <!-- / demo file [not required!] -->
<!--    <link href="/assets/stylesheets/demo.css" media="all" rel="stylesheet" type="text/css" />-->
    <!--[if lt IE 9]>
    <script src="/assets/javascripts/ie/html5shiv.js" type="text/javascript"></script>
    <script src="/assets/javascripts/ie/respond.min.js" type="text/javascript"></script>
    <![endif]-->
</head>
<body class='contrast-<?php echo $this->layout()->themeColor ?>'>
<header>
    <nav class='navbar navbar-default'>
        <a class='navbar-brand' href='index.html'>
            <a class="navbar-brand" href="<?php echo $this->url('admin/home') ?>">mSchool Admin</a>
        </a>
        <a class='toggle-nav btn pull-left' href='#'>
            <i class='icon-reorder'></i>
        </a>
        <ul class='nav'>

            <li class='dropdown dark user-menu'>
                <a class='dropdown-toggle' data-toggle='dropdown' href=''>
<!--                    <img width="23" height="23" alt="Mila Kunis" src="/assets/images/avatar.jpg" />-->
                    <span class='user-name'><?php echo $this->currentUser->getFullName() ?></span>
                    <b class='caret'></b>
                </a>
                <ul class='dropdown-menu'>
                    <li>
                        <a href='<?php echo $this->url('admin/user_edit', array('id' => $this->currentUser->id)) ?>'>
                            <i class='icon-user'></i>
                            Profile
                        </a>
                    </li>
                    <li class='divider'></li>
                    <li class=''>
                        <a href="<?php echo $this->url('admin/logout') ?>">
                            <i class='icon-signout'></i>
                            <?php echo $this->translate('Logout') ?>
                        </a>
                    </li>

                </ul>
            </li>
        </ul>

    </nav>
</header>
<div id='wrapper'>
<div id='main-nav-bg'></div>
<nav id='main-nav'>
<div class='navigation'>
    <div class='search'>
        <form action='search_results.html' method='get'>
            <div class='search-wrapper'>
                <input value="" class="search-query form-control" placeholder="Search..." autocomplete="off" name="q" type="text" />
                <button class='btn btn-link icon-search' name='button' type='submit'></button>
            </div>
        </form>
    </div>
    <ul class='nav nav-stacked'>
        <li class=''>
            <a href="<?php echo $this->url('admin/home') ?>">
                <i class='icon-dashboard'></i>
                <?php echo $this->translate('Home') ?>
            </a>
        </li>
        <li class=''>
            <a href="<?php echo $this->url('admin/accounts') ?>">
                <i class='icon-cog'></i>
                <?php echo $this->translate('Accounts') ?>
            </a>
        </li>

        <li class=''>
            <a class="dropdown-collapse <?php echo ($this->activeMenu == 'structures') ? ('in') : ('') ?>" href="#">
                <i class='icon-cogs'></i>
                <span>Structures</span>
                <i class='icon-angle-down angle-down'></i>
            </a>

            <ul class='nav nav-stacked <?php echo ($this->activeMenu == 'structures') ? ('in') : ('') ?>'>
                <li><a href="<?php echo $this->url('admin/pathways') ?>"><i class='icon-caret-right'></i><span>Pathways</span></a></li>
                <li><a href="<?php echo $this->url('admin/plans') ?>"><i class='icon-caret-right'></i><span>Plans</span></a></li>
                <li><a href="<?php echo $this->url('admin/steps') ?>"><i class='icon-caret-right'></i><span>Steps</span></a></li>
                <li><a href="<?php echo $this->url('admin/resources') ?>"><i class='icon-caret-right'></i><span>Resources</span></a></li>
            </ul>
        </li>

        <li class=''>
            <a class="dropdown-collapse <?php echo ($this->activeMenu == 'sequences') ? ('in') : ('') ?>" href="#">
                <i class='icon-cogs'></i>
                <span>Sequences</span>
                <i class='icon-angle-down angle-down'></i>
            </a>

            <ul class='nav nav-stacked <?php echo ($this->activeMenu == 'sequences') ? ('in') : ('') ?>'>
                <li><a href="<?php echo $this->url('admin/upload_pathways') ?>"><i class='icon-caret-right'></i><span>Upload</span></a></li>
<!--                <li><a href="--><?php //echo $this->url('admin/pathways_preview') ?><!--"><i class='icon-caret-right'></i><span>Preview</span></a></li>-->
            </ul>
        </li>

        <li class=''>
            <a class="dropdown-collapse <?php echo ($this->activeMenu == 'import') ? ('in') : ('') ?>" href="#">
                <i class='icon-cogs'></i>
                <span>Import</span>
                <i class='icon-angle-down angle-down'></i>
            </a>

            <ul class='nav nav-stacked <?php echo ($this->activeMenu == 'import') ? ('in') : ('') ?>'>
                <li><a href="<?php echo $this->url('admin/import_status') ?>"><i class='icon-caret-right'></i><span>Status</span></a></li>
                <li><a href="<?php echo $this->url('admin/import_history', array('type' => 'iready')) ?>"><i class='icon-caret-right'></i><span>iReady</span></a></li>
                <!--                <li><a href="--><?php //echo $this->url('admin/pathways_preview') ?><!--"><i class='icon-caret-right'></i><span>Preview</span></a></li>-->
            </ul>
        </li>

        <li class=''>
            <a href="<?php echo $this->url('admin/users') ?>">
                <i class='icon-user'></i>
                <?php echo $this->translate('Users') ?>
            </a>
        </li>

    </ul>
</div>
</nav>
<section id='content'>
    <div class='container'>
        <div class='row' id='content-wrapper'>
            <div class='col-xs-12'>

                <div class='page-header page-header-with-buttons'>
                    <h1 class='pull-left'>
<!--                        <i class='icon-dashboard'></i>-->
                        <span><?php echo $this->pageTitle ?></span>
                    </h1>
                </div>

            </div>
        </div>

        <div class="row">
            <div class="col-xs-12">

                <?php
                $flash = $this->flashMessenger();
                $flash->setMessageOpenFormat('<div%s><ul><li>')
                    ->setMessageSeparatorString('</li><li>')
                    ->setMessageCloseString('</li></ul></div>');

                echo $flash->render('error',   array('alert', 'alert-danger'));
                echo $flash->render('info',    array('alert', 'alert-info'));
                echo $flash->render('default', array('alert', 'alert-warning'));
                echo $flash->render('success', array('alert', 'alert-success'));
                ?>

                <?php echo $this->content; ?>

            </div>
        </div>

        <footer id='footer'>
            <div class='footer-wrapper'>
                <div class='row'>
                    <div class='col-sm-6 text'>
                        Copyright &copy; <?php echo date('Y') ?> mSchool
                    </div>
                    <div class='col-sm-6 buttons'>

                    </div>
                </div>
            </div>
        </footer>
        </div>
    </div>
</section>
</div>
<!-- / jquery [required] -->
<script src="/assets/javascripts/jquery/jquery.min.js" type="text/javascript"></script>
<!-- / jquery mobile (for touch events) -->
<script src="/assets/javascripts/jquery/jquery.mobile.custom.min.js" type="text/javascript"></script>
<!-- / jquery migrate (for compatibility with new jquery) [required] -->
<script src="/assets/javascripts/jquery/jquery-migrate.min.js" type="text/javascript"></script>
<!-- / jquery ui -->
<script src="/assets/javascripts/jquery/jquery-ui.min.js" type="text/javascript"></script>
<!-- / jQuery UI Touch Punch -->
<script src="/assets/javascripts/plugins/jquery_ui_touch_punch/jquery.ui.touch-punch.min.js" type="text/javascript"></script>
<!-- / bootstrap [required] -->
<script src="/assets/javascripts/bootstrap/bootstrap.js" type="text/javascript"></script>
<!-- / modernizr -->
<script src="/assets/javascripts/plugins/modernizr/modernizr.min.js" type="text/javascript"></script>
<!-- / retina -->
<script src="/assets/javascripts/plugins/retina/retina.js" type="text/javascript"></script>
<!-- / theme file [required] -->
<script src="/assets/javascripts/theme.js" type="text/javascript"></script>
<!-- / demo file [not required!] -->
<!--<script src="/assets/javascripts/demo.js" type="text/javascript"></script>-->
<!-- / START - page related files and scripts [optional] -->
<script src="/assets/javascripts/plugins/flot/excanvas.js" type="text/javascript"></script>
<script src="/assets/javascripts/plugins/flot/flot.min.js" type="text/javascript"></script>
<script src="/assets/javascripts/plugins/flot/flot.resize.js" type="text/javascript"></script>

<script src="/assets/javascripts/plugins/bootstrap_daterangepicker/bootstrap-daterangepicker.js" type="text/javascript"></script>
<script src="/assets/javascripts/plugins/common/moment.min.js" type="text/javascript"></script>
<script src="/assets/javascripts/plugins/bootbox/bootbox.min.js" type="text/javascript"></script>
<script src="/assets/javascripts/plugins/slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="/assets/javascripts/plugins/timeago/jquery.timeago.js" type="text/javascript"></script>
<script src="/assets/javascripts/plugins/common/wysihtml5.min.js" type="text/javascript"></script>
<script src="/assets/javascripts/plugins/common/bootstrap-wysihtml5.js" type="text/javascript"></script>
<script src="/assets/javascripts/plugins/fullcalendar/fullcalendar.min.js" type="text/javascript"></script>
<script src="/assets/javascripts/plugins/bootbox/bootbox.min.js" type="text/javascript"></script>

<!-- ADMIN -->
<script src="/assets/mschool/js/admin-student.js" type="text/javascript"></script>

</body>
</html>
