<div class="row">
    <div class="col-md-4">
    <?php $form->prepare(); ?>
    <?php echo $this->form()->openTag($form->setAttribute('class', 'form-inline')); ?>

    <?php $fileElement = $form->get('pathways-file'); ?>
        <div class="form-group">
            <?php echo $this->formFile($fileElement); ?>
            <?php echo $this->formElementErrors($fileElement); ?>
        </div>
    <?php
    $submit = $form->get('submit');
    echo $this->formInput($submit ->setAttribute('class', 'btn btn-primary btn-sm pull-right')->setValue('Upload'));
    echo $this->formElementErrors($submit );
    ?>
    <?php echo $this->form()->closeTag(); ?>
    </div>
</div>

<hr />

<div class="row">
    <div class="col-md-12">
        <a href="<?php echo $this->url('admin/upload_pathways_file_template') ?>" class="btn btn-info">Download File Template</a>
    </div>
</div>