<!DOCTYPE html>
<html>
<head>
    <title>mSchool</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <meta content='text/html;charset=utf-8' http-equiv='content-type'>
<!--    <meta content='Flat administration template for Twitter Bootstrap. Twitter Bootstrap 3 template with Ruby on Rails support.' name='description'>-->
    <link rel="icon" type="image/png" href="/assets/mschool/images/favicon.png">
<!--    <link href='/assets/images/meta_icons/favicon.ico' rel='shortcut icon' type='image/x-icon'>-->
<!--    <link href='/assets/images/meta_icons/apple-touch-icon.png' rel='apple-touch-icon-precomposed'>-->
<!--    <link href='/assets/images/meta_icons/apple-touch-icon-57x57.png' rel='apple-touch-icon-precomposed' sizes='57x57'>-->
<!--    <link href='/assets/images/meta_icons/apple-touch-icon-72x72.png' rel='apple-touch-icon-precomposed' sizes='72x72'>-->
<!--    <link href='/assets/images/meta_icons/apple-touch-icon-114x114.png' rel='apple-touch-icon-precomposed' sizes='114x114'>-->
<!--    <link href='/assets/images/meta_icons/apple-touch-icon-144x144.png' rel='apple-touch-icon-precomposed' sizes='144x144'>-->
    <!-- / START - page related stylesheets [optional] -->
    <link href="/assets/stylesheets/plugins/bootstrap_daterangepicker/bootstrap-daterangepicker.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/assets/stylesheets/plugins/fullcalendar/fullcalendar.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/assets/stylesheets/plugins/common/bootstrap-wysihtml5.css" media="all" rel="stylesheet" type="text/css" />
    <!-- / END - page related stylesheets [optional] -->
    <!-- / bootstrap [required] -->
    <link href="/assets/stylesheets/bootstrap/bootstrap.css" media="all" rel="stylesheet" type="text/css" />
    <!-- / theme file [required] -->
    <link href="/assets/stylesheets/light-theme.css" media="all" id="color-settings-body-color" rel="stylesheet" type="text/css" />
    <!-- / coloring file [optional] (if you are going to use custom contrast color) -->
    <link href="/assets/stylesheets/theme-colors.css" media="all" rel="stylesheet" type="text/css" />
    <!-- / demo file [not required!] -->
    <!--    <link href="/assets/stylesheets/demo.css" media="all" rel="stylesheet" type="text/css" />-->
    <link href="/assets/mschool/stylesheets/mschool-teacher.css" media="all" rel="stylesheet" type="text/css" />
    <!--[if lt IE 9]>
    <script src="/assets/javascripts/ie/html5shiv.js" type="text/javascript"></script>
    <script src="/assets/javascripts/ie/respond.min.js" type="text/javascript"></script>
    <![endif]-->

    <script src="/assets/d3/d3.min.js"></script>

</head>
<body class='contrast-<?php echo $this->layout()->themeColor ?> main-nav-closed'>
<header>
    <nav class='navbar navbar-default'>
        <a class='navbar-brand' href='index.html'>
            <a class="navbar-brand" href="<?php echo $this->url('mschool/home') ?>">mSchool</a>
        </a>

        <ul class='nav'>
            <li class="light">
                <a class="" href="<?php echo $this->url('mschool/teacher_progress'); ?>">
                    <i class="icon-bar-chart"></i>
                    Progress
                </a>
            </li>
            <li class="light">
                <a class="" href="<?php echo $this->url('mschool/teacher_assessment'); ?>">
                    <i class="icon-signal"></i>
                    Assessment
                </a>
            </li>
            <li class="light">
                <a class="" href="<?php echo $this->url('mschool/teacher_student_accounts'); ?>">
                    <i class="icon-group"></i>
                    Student Accounts
                </a>
            </li>

            <li class='dropdown dark'>
                <a href="<?php echo $this->url('mschool/logout') ?>">
                    <i class='icon-signout'></i>
                    <?php echo $this->translate('Logout') ?>
                </a>
            </li>

<!--            <li class="dropdown light only-icon">-->
<!--                <a class="dropdown-toggle" data-toggle="dropdown" href="#">-->
<!--                    <i class="icon-cog"></i>-->
<!--                </a>-->
<!--                <ul class="dropdown-menu color-settings">-->
<!---->
<!--                </ul>-->
<!--            </li>-->

<!--            <li class="dropdown medium only-icon widget">-->
<!--                <a class="dropdown-toggle" data-toggle="dropdown" href="#">-->
<!--                    <i class="icon-rss"></i>-->
<!--                    <div class="label">5</div>-->
<!--                </a>-->
<!--                <ul class="dropdown-menu">-->
<!--                    <li>-->
<!--                        <a href="#">-->
<!--                            <div class="widget-body">-->
<!--                                <div class="pull-left icon">-->
<!--                                    <i class="icon-user text-success"></i>-->
<!--                                </div>-->
<!--                                <div class="pull-left text">-->
<!--                                    John Doe signed on-->
<!--                                    <small class="text-muted">just now</small>-->
<!--                                </div>-->
<!--                            </div>-->
<!--                        </a>-->
<!--                    </li>-->
<!--                    <li class="divider"></li>-->
<!--                    <li>-->
<!--                        <a href="#">-->
<!--                            <div class="widget-body">-->
<!--                                <div class="pull-left icon">-->
<!--                                    <i class="icon-user text-success"></i>-->
<!--                                </div>-->
<!--                                <div class="pull-left text">-->
<!--                                    Jane Doe signed on-->
<!--                                    <small class="text-muted">last week</small>-->
<!--                                </div>-->
<!--                            </div>-->
<!--                        </a>-->
<!--                    </li>-->
<!--                    <li class="divider"></li>-->
<!--                </ul>-->
<!--            </li>-->

        </ul>

<!--        <form action="search_results.html" class="navbar-form navbar-right hidden-xs" method="get">-->
<!--            <button class="btn btn-link icon-search" name="button" type="submit"></button>-->
<!--            <div class="form-group">-->
<!--                <input value="" class="form-control" placeholder="Search..." autocomplete="off" id="q_header" name="q" type="text">-->
<!--            </div>-->
<!--        </form>-->

    </nav>
</header>
<div id='wrapper'>
    <div id='main-nav-bg'></div>
    <nav id='main-nav'>
<!--        <div class='navigation'>-->
<!--            <ul class="nav nav-stacked">-->
<!--                <li class="active">-->
<!--                    &nbsp;-->
<!--                </li>-->
<!--            </ul>-->
<!---->
<!--        </div>-->
    </nav>
    <section id='content'>
        <div class='container'>

            <div class="row">
                <div class="col-xs-12">

                    <?php
                    $flash = $this->flashMessenger();
                    $flash->setMessageOpenFormat('<div%s><ul><li>')
                        ->setMessageSeparatorString('</li><li>')
                        ->setMessageCloseString('</li></ul></div>');

                    echo $flash->render('error',   array('alert', 'alert-danger'));
                    echo $flash->render('info',    array('alert', 'alert-info'));
                    echo $flash->render('default', array('alert', 'alert-warning'));
                    echo $flash->render('success', array('alert', 'alert-success'));
                    ?>

                    <?php echo $this->content; ?>

                </div>
            </div>

            <footer id='footer'>
                <div class='footer-wrapper'>
                    <div class='row'>
                        <div class='col-sm-6 text'>
                            Copyright &copy; <?php echo date('Y') ?> mSchool
                        </div>
                        <div class='col-sm-6 buttons'>

                        </div>
                    </div>
                </div>
            </footer>
        </div>
</div>
</section>
</div>
<!-- / jquery [required] -->
<script src="/assets/javascripts/jquery/jquery.min.js" type="text/javascript"></script>
<!-- / jquery mobile (for touch events) -->
<script src="/assets/javascripts/jquery/jquery.mobile.custom.min.js" type="text/javascript"></script>
<!-- / jquery migrate (for compatibility with new jquery) [required] -->
<script src="/assets/javascripts/jquery/jquery-migrate.min.js" type="text/javascript"></script>
<!-- / jquery ui -->
<script src="/assets/javascripts/jquery/jquery-ui.min.js" type="text/javascript"></script>
<!-- / jQuery UI Touch Punch -->
<script src="/assets/javascripts/plugins/jquery_ui_touch_punch/jquery.ui.touch-punch.min.js" type="text/javascript"></script>
<!-- / bootstrap [required] -->
<script src="/assets/javascripts/bootstrap/bootstrap.js" type="text/javascript"></script>
<!-- / modernizr -->
<script src="/assets/javascripts/plugins/modernizr/modernizr.min.js" type="text/javascript"></script>
<!-- / retina -->
<script src="/assets/javascripts/plugins/retina/retina.js" type="text/javascript"></script>
<!-- / theme file [required] -->
<script src="/assets/javascripts/theme.js" type="text/javascript"></script>
<!-- / demo file [not required!] -->
<!--<script src="/assets/javascripts/demo.js" type="text/javascript"></script>-->
<!-- / START - page related files and scripts [optional] -->
<script src="/assets/javascripts/plugins/flot/excanvas.js" type="text/javascript"></script>
<script src="/assets/javascripts/plugins/flot/flot.min.js" type="text/javascript"></script>
<script src="/assets/javascripts/plugins/flot/flot.resize.js" type="text/javascript"></script>

<script src="/assets/javascripts/plugins/bootstrap_daterangepicker/bootstrap-daterangepicker.js" type="text/javascript"></script>
<script src="/assets/javascripts/plugins/common/moment.min.js" type="text/javascript"></script>
<script src="/assets/javascripts/plugins/bootbox/bootbox.min.js" type="text/javascript"></script>
<script src="/assets/javascripts/plugins/slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="/assets/javascripts/plugins/timeago/jquery.timeago.js" type="text/javascript"></script>
<script src="/assets/javascripts/plugins/common/wysihtml5.min.js" type="text/javascript"></script>
<script src="/assets/javascripts/plugins/common/bootstrap-wysihtml5.js" type="text/javascript"></script>
<script src="/assets/javascripts/plugins/fullcalendar/fullcalendar.min.js" type="text/javascript"></script>
<script src="/assets/javascripts/plugins/bootbox/bootbox.min.js" type="text/javascript"></script>

<!-- MSCHOOL -->
<script src="/assets/mschool/js/student-password.js" type="text/javascript"></script>

<!-- DASHBOARD DEMOS -->
<script src="/assets/mschool/js/teacher.js" type="text/javascript"></script>
<!--<script src="/assets/mschool/js/student-progress.js" type="text/javascript"></script>-->
<!--<script src="/assets/mschool/js/student-dashboard.js" type="text/javascript"></script>-->
<!--<script src="/assets/mschool/js/coach-dashboard.js" type="text/javascript"></script>-->
<!--<script src="/assets/mschool/js/student-progress.js" type="text/javascript"></script>-->
<!-- END DASHBOARD DEMOS -->


<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-35838158-3', 'auto');
    ga('require', 'linkid', 'linkid.js');
    ga('send', 'pageview');

</script>


<script>
    dataLayer = [];
</script>



<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-MXC2GV"
                  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-MXC2GV');</script>
<!-- End Google Tag Manager -->


<?php // LOADED BY /assets/mschool/js/teacher.js ?>
<div id="signup-welcome-message" style="display: none" data-display="<?php echo ($this->displayWelcome) ? ('yes') : ('no') ?>">
    <p>This is where you will find mSchool information for each of your students. Since you don't have any student accounts yet, we've created some demo classes to show you what it will look like once you set up your own class.</p>

    <p>We’re proud that mSchool collects student data from multiple learning programs so you don’t have too. Poke around and see what you think. Here are a few ways we streamline multiple data sources into one place:</p>

    <h4>Time on Math</h4>
    <p>We collect time on task data from multiple programs to show you the total time your students spend working at a glance.</p>

    <h4>Learning Points</h4>
    <p>We collect progress data from multiple programs to give you an overall view on how your students are performing.</p>

    <h4>What Students Are Working On</h4>
    <p>We show you individual playlists so you know what each student is up to at all times.</p>

    <p>Our set up team will be in touch shortly to work with you on creating real accounts for your students.</p>

    <p>Any questions? Feel free to reach out to us at <a href="mailto:info@mschools.org">info@mschools.org</a></p>
</div>

</body>
</html>
