<?php $boxOpenStyle = ''; ?>

<?php foreach($this->sequenceGroups as $sequenceId => $sequenceRows): ?>
    <div class="box bordered-box blue-border <?php echo $boxOpenStyle ?>" style="margin-bottom:0;">
        <div class="box-header <?php echo ($sequenceRows[0]['sequence_is_active']) ? ('blue-background') : ('muted-background'); ?> ">
            <div class="title">
                Sequence <?php echo ($sequenceRows[0]['sequence_is_default']) ? ('Default') : ($sequenceId) ?>
                <?php if (!$sequenceRows[0]['sequence_is_active']): ?>
                    <span class="label label-contrast">(Inactive)</span>
                <?php endif; ?>
                <?php if ($sequenceRows[0]['sequence_is_complete']): ?>
                    <span class="label label-contrast">Completed: <?php echo date_create($sequenceRows[0]['sequence_completed_at'])->format('m/d/Y h:i:s A'); ?></span>
                <?php endif; ?>

            </div>
            <div class="actions">
                <a class="btn box-collapse btn-xs btn-link" href="#"><i></i>
                </a>
            </div>
        </div>

        <div class="box-content box-no-padding">
            <div class="responsive-table">
                <div class="scrollable-area">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Pathway</th>
                            <th>Pathway Code</th>
                            <th>Plan Group</th>
                            <th>Plan</th>
                            <th>Plan Code</th>
                            <th>Step Code</th>
                            <th>Status</th>
                        </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($sequenceRows as $row): ?>
                                <tr class="<?php echo ($row['plan_group'] % 2 == 0) ? ('plan-group-highlight-one') : ('plan-group-highlight-two')  ?>">
                                    <td><?php echo $row['pathway_name'] ?></td>
                                    <td><?php echo $row['pathway_short_code'] ?></td>
                                    <td><?php echo $row['plan_group'] ?></td>
                                    <td><?php echo $row['plan_name'] ?></td>
                                    <td><?php echo $row['plan_short_code'] ?></td>
                                    <td><?php echo $row['step_short_code'] ?></td>
                                    <td>
                                        <?php if($row['ss_is_complete'] == 1): ?>
                                            <span class="label label-success">Complete</span>
                                            <?php echo date('m/d/Y h:i:s A', strtotime($row['ss_completed_at'])); ?>
                                        <?php elseif($row['ss_skipped_at']): ?>
                                            <span class="label label-warning">Skipped</span>
                                            <?php echo date_create($row['ss_skipped_at'])->format('m/d/Y h:i:s A'); ?>
                                        <?php elseif (!$row['sequence_is_active']): ?>
                                            <span class="label label-default">Inactive</span>
                                        <?php else: ?>
                                            &nbsp;
                                        <?php endif; ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <hr class="hr-double">

    <?php // CLOSE OLD BOXES ?>
    <?php if ($boxOpenStyle == '') $boxOpenStyle = 'box-collapsed'; ?>

<?php endforeach; ?>

