<div class="row">
    <div class="col-md-12">
        <a href="/import/status" class="btn btn-default">Status</a>
    </div>
</div>

<h1>Import History: <?php echo $this->type; ?></h1>

<?php if ($this->type == 'iready'): ?>
    <?php echo $this->partial('admin/import/history-iready.phtml', array('iready' => $this->data)); ?>
<?php elseif ($this->type == 'digitwhiz-mastery'): ?>
    <?php echo $this->partial('admin/import/history-digitwhiz-mastery.phtml', array('data' => $this->data)); ?>
<?php elseif ($this->type == 'digitwhiz-time'): ?>
    <?php echo $this->partial('admin/import/history-digitwhiz-time.phtml', array('data' => $this->data)); ?>
<?php elseif ($this->type == 'dreambox-usage'): ?>
    <?php echo $this->partial('admin/import/history-dreambox-usage.phtml', array('data' => $this->data)); ?>
<?php elseif ($this->type == 'dreambox-standards'): ?>
    <?php echo $this->partial('admin/import/history-dreambox-standards.phtml', array('data' => $this->data)); ?>
<?php elseif ($this->type == 'ttm-student'): ?>
    <?php echo $this->partial('admin/import/history-ttm-student.phtml', array('data' => $this->data)); ?>
<?php elseif ($this->type == 'ttm-overview'): ?>
    <?php echo $this->partial('admin/import/history-ttm-overview.phtml', array('data' => $this->data)); ?>
<?php endif; ?>