<div class="row">
    <div class="col-md-12">
        <a href="/import/status" class="btn btn-default">Status</a>
    </div>
</div>

<h1>Import History: <?php echo $this->type; ?></h1>

<?php if ($this->type == 'iready'): ?>
    <?php echo $this->partial('admin/import/history-iready.phtml', array('iready' => $this->data)); ?>
<?php elseif ($this->type == 'dreambox-usage'): ?>
    <?php echo $this->partial('admin/import/history-dreambox-usage.phtml', array('data' => $this->data)); ?>
<?php endif; ?>