<h1>Import Status</h1>

<?php
    $listContents = function($entry) {
        $listing = '';

        echo "<ul>";
        foreach($entry['contents'] as $child) {
            $cp = $child['path'];
            $cn = basename($cp);
            if ($cn == 'completed') continue;
            if ($child['is_dir']) $cn .= '/';

            $cp = htmlspecialchars($cp);
            //$link = getPath("?path=".htmlspecialchars($cp));
            echo "<li>" . $cp . "</li>";
        }
        echo "</ul>";

    };

?>

<h2>DigitWhiz - Mastery</h2>
<div class="row">
    <div class="col-md-12">
        <a href="/import/digitwhiz-mastery" class="btn btn-primary">Import</a>
        <a href="/import/history/digitwhiz-mastery" class="btn btn-info">History</a>
    </div>
</div>
<?php
$entry = $this->dropbox->getMetadataWithChildren('/digitwhiz/import/mastery');
$listContents($entry);
?>

<h2>DigitWhiz - Time</h2>
<div class="row">
    <div class="col-md-12">
        <a href="/import/digitwhiz-time" class="btn btn-primary">Import</a>
        <a href="/import/history/digitwhiz-time" class="btn btn-info">History</a>
    </div>
</div>
<?php
$entry = $this->dropbox->getMetadataWithChildren('/digitwhiz/import/time');
$listContents($entry);
?>

<h2>Dreambox - Usage</h2>
<div class="row">
    <div class="col-md-12">
        <a href="/import/dreambox-usage" class="btn btn-primary">Import</a>
        <a href="/import/history/dreambox-usage" class="btn btn-info">History</a>
    </div>
</div>
<?php
    $entry = $this->dropbox->getMetadataWithChildren('/dreambox/import/usage');
    $listContents($entry);
?>

<h2>Dreambox - Standards</h2>
<div class="row">
    <div class="col-md-12">
        <a href="/import/dreambox-standards" class="btn btn-primary">Import</a>
        <a href="/import/history/dreambox-standards" class="btn btn-info">History</a>
    </div>
</div>
<?php
$entry = $this->dropbox->getMetadataWithChildren('/dreambox/import/standards');
$listContents($entry);
?>

<h2>iReady</h2>
<div class="row">
    <div class="col-md-12">
        <a href="/import/iready" class="btn btn-primary">Import</a>
        <a href="/import/history/iready" class="btn btn-info">History</a>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <?php
            $entry = $this->dropbox->getMetadataWithChildren('/iready');
            $listContents($entry);
        ?>
    </div>
</div>

<h2>ST Math - Progress</h2>
<div class="row">
    <div class="col-md-12">
        <a href="/import/stmath-progress" class="btn btn-primary">Import</a>
        <a href="/import/history/stmath-progress" class="btn btn-info">History</a>
    </div>
</div>
<?php
$entry = $this->dropbox->getMetadataWithChildren('/stmath/import/progress');
$listContents($entry);
?>

<h2>ST Math - Student</h2>
<div class="row">
    <div class="col-md-12">
        <a href="/import/stmath-student" class="btn btn-primary">Import</a>
        <a href="/import/history/stmath-student" class="btn btn-info">History</a>
    </div>
</div>
<?php
$entry = $this->dropbox->getMetadataWithChildren('/stmath/import/student');
$listContents($entry);
?>

<h2>ST Math - Usage</h2>
<div class="row">
    <div class="col-md-12">
        <a href="/import/stmath-usage" class="btn btn-primary">Import</a>
        <a href="/import/history/stmath-usage" class="btn btn-info">History</a>
    </div>
</div>
<?php
    $entry = $this->dropbox->getMetadataWithChildren('/stmath/import/usage');
    $listContents($entry);
?>

<h2>Think Through Math - Student</h2>
<div class="row">
    <div class="col-md-12">
        <a href="/import/ttm-student" class="btn btn-primary">Import</a>
        <a href="/import/history/ttm-student" class="btn btn-info">History</a>
    </div>
</div>
<?php
    $entry = $this->dropbox->getMetadataWithChildren('/thinkthroughmath/import/student');
    $listContents($entry);
?>

<h2>Think Through Math - Overview</h2>
<div class="row">
    <div class="col-md-12">
        <a href="/import/ttm-overview" class="btn btn-primary">Import</a>
        <a href="/import/history/ttm-overview" class="btn btn-info">History</a>
    </div>
</div>
<?php
$entry = $this->dropbox->getMetadataWithChildren('/thinkthroughmath/import/overview');
$listContents($entry);
?>