<div class="alert alert-success alert-dismissable">
    <a class="close" data-dismiss="alert" href="#">×
    </a>

    <h4>
        <i class="icon-ok-sign"></i>
        Welcome to mSchool
    </h4>
</div>

<p>
    <?php if ($hasSteps): ?>
        <a class="btn btn-primary btn-lg" href="<?php echo $this->url('mschool/pathway') ?>" role="button">Go to your lessons!</a>
    <?php else: ?>
        Great job! You're all done for the day.
    <?php endif; ?>
</p>