<div class="alert alert-success">
    <h4>
        <i class="icon-ok-sign"></i>
        Welcome to mSchool
    </h4>
</div>

<p>
    <?php if ($hasSteps): ?>
        <a class="btn btn-primary btn-lg" href="<?php echo $this->url('mschool/pathway') ?>" role="button">Go to your
            lessons!</a>
    <?php else: ?>
    <h3>Great job! You finished your pathway.</h3>
    <?php endif; ?>
</p>

<?php if (count($extraCreditOptions)): ?>
    <h4>Want to keep growing your brain for extra credit?</h4>
    <p>Pick your favorite activity.</p>

    <div class="row">

        <?php foreach ($extraCreditOptions as $currResource): ?>
            <div class="col-sm-2">
                <a href="<?php echo $this->url('mschool/pathway_extra_credit', ['r_id' => $currResource->id]); ?>">
                    <img src="/assets/mschool/images/resources/<?php echo $currResource->image ?>" class="img-responsive" />
                </a>
            </div>
        <?php endforeach; ?>

    </div>

<?php endif; ?>

<hr />

<div class="row">
    <div class="col-sm-12">
        <div class="box">
            <div class="box-header">
                <div class="title">
                    Your Progress
                </div>
                <div class="actions">
                </div>
            </div>
            <div class="box-content">
                <div id="stats-chart1" style="padding: 0px; position: relative; height: 200px;">
                    &nbsp;
                </div>
            </div>
        </div>
    </div>
</div>