<div class="row">
    <div class="col-xs-12">
        <div class="page-header page-header-with-buttons">
            <h1 class="pull-left">
                <i class="icon-signal"></i>
                <span>Assessment</span>
            </h1>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <?php echo $this->partial('m-school/teacher/common/class-switcher.phtml', array('mclasses' => $mclasses, 'current' => $mclass, 'url' => '/teacher/assessment')); ?>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <h1><?php echo $mclass->name ?></h1>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <h2>Class Average</h2>
        <div class="assessment-class-average" style="background-color: white" data-mclass-id="<?php echo $mclass->id ?>"></div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <h2>Student Placements</h2>
        <div class="assessment-student-placement" style="background-color: white" data-mclass-id="<?php echo $mclass->id ?>"></div>
    </div>
</div>