<h1>My Classes</h1>

<div class="row">
    <div class="col-md-4">

        <table class="table table-stripped">
            <thead>
            <tr>
                <th>Class</th>
                <th>&nbsp;</th>
            </tr>
            </thead>
            <tbody>
                <?php foreach ($mclasses as $class): ?>
                <tr>
                    <td>
                        <a href="<?php echo $this->url("mschool/teacher_class_dashboard", ['id' => $class->id]); ?>">
                            <?php echo $class->name ?>
                            <?php echo $class->id ?>
                        </a>
                    </td>
                    <td></td>
                </tr>
                <?php endforeach; ?>
            </tbody>

        </table>

    </div>
</div>