<div class="row">
    <div class="col-xs-12">
        <div class="page-header page-header-with-buttons">
            <h1 class="pull-left">
                <i class="icon-bar-chart"></i>
                <span>Progress</span>
            </h1>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <?php echo $this->partial('m-school/teacher/common/class-switcher.phtml', array('mclasses' => $mclasses, 'current' => $mclass, 'url' => '/teacher/progress')); ?>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <h1><?php echo $mclass->name ?></h1>
    </div>
</div>

<div class="row">
    <div class="col-xs-12 col-md-6">
        <h2>Time on Math</h2>
        <div class="progress-time-on-math" style="background-color: white" data-mclass-id="<?php echo $mclass->id ?>"></div>
    </div>
    <div class="col-xs-12 col-md-6">
        <h2>Learning Points</h2>
        <div class="progress-learning-points" style="background-color: white" data-mclass-id="<?php echo $mclass->id ?>"></div>
    </div>
</div>


<div class="row">

    <div class="col-md-12">

        <h2>What are my students working on?</h2>

        <table class="table table-bordered table-hover table-striped">
            <thead>
                <tr>
                    <th>Student</th>
                    <th>Upcoming Resources</th>
                </tr>
            </thead>

            <tbody>

                <?php foreach($students as $currStudent): ?>
                    <tr>
                        <td class="col-md-3 upcoming-resource-student-name"><?php echo $currStudent->getFullName() ?></td>
                        <td>
                            <div class="student-resource-map" data-student-id="<?php echo $currStudent->id ?>">

                                <div class="loading-resource-map">
                                    <img src="/assets/images/ajax-loaders/17.gif"> Loading...
                                </div>

                                <div class="plan-groups" style="display: none">

                                </div>

                                <div class="no-resource-map" style="display: none">
                                    No upcoming resources found.
                                </div>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>

            </tbody>

        </table>

    </div>

</div>