<div class="row">
    <div class="col-xs-12">
        <div class="page-header page-header-with-buttons">
            <h1 class="pull-left">
                <i class="icon-bar-chart"></i>
                <span>Progress</span>
            </h1>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <?php echo $this->partial('m-school/teacher/common/class-switcher.phtml', array('mclasses' => $mclasses, 'current' => $mclass, 'url' => '/teacher/progress')); ?>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <h1><?php echo $mclass->name ?></h1>
    </div>
</div>

<div class="row">
    <div class="col-xs-12 col-md-6">
        <h2>Time on Math</h2>
        <div class="progress-time-on-math" style="background-color: white" data-mclass-id="<?php echo $mclass->id ?>"></div>
    </div>
    <div class="col-xs-12 col-md-6">
        <h2>Learning Points</h2>
        <div class="progress-learning-points" style="background-color: white" data-mclass-id="<?php echo $mclass->id ?>"></div>
    </div>
</div>


<div class="row">

    <div class="col-md-12">

                <?php foreach($students as $currStudent): ?>

                    <div class="box" style="padding-bottom: 12px">

                        <div class="box-content">

                            <div class="student-resource-map" data-student-id="<?php echo $currStudent->id ?>">
                                <h4><?php echo $currStudent->getFullName() ?></h4>

                                <div class="loading-resource-map">
                                    <img src="/assets/images/ajax-loaders/17.gif"> Loading...
                                </div>

                                <div class="plan-groups" style="display: none">

                                </div>

                                <div class="no-resource-map alert alert-warning alert-dismissable" style="display: none">
                                    No upcoming resources found.
                                </div>
                            </div>

                        </div>

                    </div>


                <?php endforeach; ?>

        </div>

    </div>

</div>