<h1>Student Progress</h1>

<div class="row">

    <div class="col-xs-3">

        <div class="box">
            <div class="box-header">
                <div class="title">
                    <i class="icon-group"></i>
                    Your Stats
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="box-content box-statistic">
                        <small>You spent</small>
                        <h3 class="title text-primary">43 minutes</h3>
                        <small>on mSchool</small>
                        <div class="text-primary icon-time align-right"></div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <div class="col-xs-3">

        <div class="box">
            <div class="box-header">
                <div class="title">
                    &nbsp;
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="box-content box-statistic">
                        <small>Last week you gained</small>
                        <h3 class="title text-success">18</h3>
                        <small>learning points.</small>
                        <div class="text-success icon-ok align-right"></div>
                    </div>
                </div>
            </div>
        </div>

    </div>


</div>