<h1>Student Progress</h1>

<div class="row">

    <div class="col-xs-3">

        <div class="box">
            <div class="box-header">
                <div class="title">
                    <i class="icon-user"></i>
                    Your Stats
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="box-content box-statistic">
                        <small>You spent</small>
                        <h3 class="title text-primary">43 minutes</h3>
                        <small>on mSchool</small>
                        <div class="text-primary icon-time align-right"></div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <div class="col-xs-3">

        <div class="box">
            <div class="box-header">
                <div class="title">
                    &nbsp;
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="box-content box-statistic">
                        <small>Last week you gained</small>
                        <h3 class="title text-success">18</h3>
                        <small>learning points.</small>
                        <div class="text-success icon-ok align-right"></div>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>

<div class="row">
    <div class="col-sm-6">
        <div class="box">
            <div class="box-header">
                <div class="title">
                    Time on Task
                </div>
                <div class="actions">
                    <a class="btn box-remove btn-xs btn-link" href="#"><i class="icon-remove"></i>
                    </a>

                    <a class="btn box-collapse btn-xs btn-link" href="#"><i></i>
                    </a>
                </div>
            </div>
            <div class="box-content">
                <div id="stats-chart7" style="padding: 0px; position: relative; height: 200px;">

                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-6">
        <div class="box">
            <div class="box-header">
                <div class="title">
                    Learning Points
                </div>
                <div class="actions">
                    <a class="btn box-remove btn-xs btn-link" href="#"><i class="icon-remove"></i>
                    </a>

                    <a class="btn box-collapse btn-xs btn-link" href="#"><i></i>
                    </a>
                </div>
            </div>
            <div class="box-content">
                <div id="learning-points" style="padding: 0px; position: relative; height: 200px;">

                </div>
            </div>
        </div>
    </div>
</div>