<h1><?php echo $this->student->getFullName(); ?>'s <?php echo $this->mclass->name ?> Password</h1>
<hr>

<div class="row">
        <div class="col-md-2">
            <p><label class="control-label" for="">Current Password</label></p>
            <a href="" class="btn btn-danger btn-xs password-reveal">Click to reveal</a>
            <a href="" class="btn btn-primary btn-xs password-hide" style="display: none">Click to hide</a>
            <?php
            $password = $student->getUnencryptedPassword();
            ?>
            <span class="hidden-password">
                <?php echo str_pad('', strlen($password), '*'); ?>
            </span>
            <span class="visible-password" style="display: none">
                <?php echo $password; ?>
            </span>
        </div>
</div>

<?php
/*
$form = $this->form;
$form->prepare();

$form->setAttribute('method', 'post');

echo $this->form()->openTag($form->setAttribute('class', 'form'));
?>

<div class="row">
    <div class="col-md-2">
        <label class="control-label" for="username">Username</label>
        <p class="form-control-static"><?php echo $this->student->username; ?></p>
    </div>
</div>

<div class="row">
    <div class="form-group <?php echo (!$form->get('password')->getMessages()) ?: ('has-error') ?>">
        <div class="col-md-2">
            <label class="control-label" for="username">Password</label>
            <?php
            $password = $form->get('password');
            echo $this->formInput($password->setAttribute('class', 'form-control')->setAttribute('placeholder', ''));
            echo $this->formElementErrors($password);
            ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="form-group <?php echo (!$form->get('password_confirm')->getMessages()) ?: ('has-error') ?>">
        <div class="col-md-2">
            <label class="control-label" for="username">Password Confirmation</label>
            <?php
            $passwordConfirm = $form->get('password_confirm');
            echo $this->formInput($passwordConfirm->setAttribute('class', 'form-control')->setAttribute('placeholder', ''));
            echo $this->formElementErrors($passwordConfirm);
            ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="form-group">
        <div class="col-md-2">
            <label class="control-label" for=""></label>
            <?php
            $submit = $form->get('submit');
            echo $this->formInput($submit ->setAttribute('class', 'btn btn-primary btn-block')->setValue('Update'));
            echo $this->formElementErrors($submit );
            ?>
        </div>
    </div>
</div>

<div class="row" style="padding-top: 12px">
    <div class="col-md-2">
        <a href="<?php echo $this->url('mschool/teacher_dashboard') ?>" class="btn btn-default btn-sm">Cancel</a>
    </div>
</div>

<?php echo $this->form()->closeTag() ?>

*/ ?>

