<div class='row'>
    <div class='col-md-12'>
        <h1 class='text-center title'>Admin Login</h1>

        <?php

        $form = $this->form;
        $form->prepare();

        $form->setAttribute('method', 'post');

        echo $this->form()->openTag($form->setAttribute('class', 'validate-form'));
        ?>

        <div class='form-group <?php echo (!$form->get('username')->getMessages()) ?: ('has-error') ?>'>
            <div class='controls with-icon-over-input'>
                <?php
                    $username = $form->get('username');
                    echo $this->formInput($username->setAttribute('class', 'form-control')->setAttribute('placeholder', 'Username'));
                    echo $this->formElementErrors($username);
                ?>
<!--                <input value="" placeholder="E-mail" class="form-control" data-rule-required="true" name="email" type="text" />-->
                <i class='icon-user text-muted'></i>
            </div>
        </div>

        <div class='form-group <?php echo (!$form->get('password')->getMessages()) ?: ('has-error') ?>'>
            <div class='controls with-icon-over-input'>
                <?php
                    $password = $form->get('password');
                    echo $this->formInput($password->setAttribute('class', 'form-control')->setAttribute('placeholder', 'Password'));
                    echo $this->formElementErrors($password);
                ?>
<!--                <input value="" placeholder="Password" class="form-control" data-rule-required="true" name="password" type="password" />-->
                <i class='icon-lock text-muted'></i>
            </div>
        </div>

        <?php
            $submit = $form->get('submit');
            echo $this->formInput($submit ->setAttribute('class', 'btn btn-primary btn-block')->setValue('Sign in'));
            echo $this->formElementErrors($submit );
        ?>

        <?php echo $this->form()->closeTag() ?>
    </div>
</div>
