<div class='row'>
    <div class='col-md-12'>

        <h1 class='text-center title'>Teacher Login</h1>
        <?php

        $form = $this->form;
        $form->prepare();

        $form->setAttribute('method', 'post');

        echo $this->form()->openTag($form->setAttribute('class', 'validate-form'));
        ?>

        <div class='form-group <?php echo (!$form->get('username')->getMessages()) ?: ('has-error') ?>'>
            <div class='controls with-icon-over-input'>
                <?php
                $username = $form->get('username');
                echo $this->formInput($username->setAttribute('class', 'form-control')->setAttribute('placeholder', 'Email'));
                echo $this->formElementErrors($username);
                ?>
                <!--                <input value="" placeholder="E-mail" class="form-control" data-rule-required="true" name="email" type="text" />-->
                <i class='icon-user text-muted'></i>
            </div>
        </div>

        <div class='form-group <?php echo (!$form->get('password')->getMessages()) ?: ('has-error') ?>'>
            <div class='controls with-icon-over-input'>
                <?php
                $password = $form->get('password');
                echo $this->formInput($password->setAttribute('class', 'form-control')->setAttribute('placeholder', 'Password'));
                echo $this->formElementErrors($password);
                ?>
                <!--                <input value="" placeholder="Password" class="form-control" data-rule-required="true" name="password" type="password" />-->
                <i class='icon-lock text-muted'></i>
            </div>
        </div>

        <?php
        $submit = $form->get('submit');
        echo $this->formInput($submit ->setAttribute('class', 'btn btn-primary btn-block')->setValue('Sign in'));
        echo $this->formElementErrors($submit );
        ?>

        <?php echo $this->form()->closeTag() ?>
    </div>
</div>


<?php

return;

/** DEAD */

?>

<div class="row">
    <div class="col-md-12 text-center">
        <img src="/img/logo.png" width="200" />
        <h2>Teacher Login</h2>
    </div>
</div>

<?php

$form = $this->form;
$form->prepare();

$form->setAttribute('method', 'post');

echo $this->form()->openTag($form->setAttribute('class', 'form'));
?>

<div class="row">
    <div class="form-group <?php echo (!$form->get('username')->getMessages()) ?: ('has-error') ?>">
        <div class="col-md-offset-4 col-md-4">
            <label class="control-label" for="username">Username</label>
            <?php
            $username = $form->get('username');
            echo $this->formInput($username->setAttribute('class', 'form-control')->setAttribute('placeholder', ''));
            echo $this->formElementErrors($username);
            ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="form-group <?php echo (!$form->get('password')->getMessages()) ?: ('has-error') ?>">
        <div class="col-md-offset-4 col-md-4">
            <label class="control-label" for="password">Password</label>
            <?php
            $password = $form->get('password');
            echo $this->formInput($password->setAttribute('class', 'form-control')->setAttribute('placeholder', ''));
            echo $this->formElementErrors($password);
            ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="form-group">
        <div class="col-md-offset-4 col-md-2">
            <label class="control-label" for=""></label>
            <?php
            $submit = $form->get('submit');
            echo $this->formInput($submit ->setAttribute('class', 'btn btn-primary btn-block')->setValue('Login'));
            echo $this->formElementErrors($submit );
            ?>
        </div>
    </div>
</div>

<?php echo $this->form()->closeTag() ?>


</div>

