<div class="row" style="padding-top: 12px">
    <div class="col-md-12 text-right">
        <a href="<?php echo $this->url('admin/user_add') ?>" class="btn btn-primary">Add User</a>
    </div>
</div>

<div class="row" style="padding-top: 12px">
    <div class="col-md-12">

        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Username</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($users as $user): ?>
                    <tr>
                        <td>
                            <a href="<?php echo $this->url('admin/user_edit', array('id' => $user->id)) ?>">
                                <?php echo $user->firstName ?> <?php echo $user->lastName ?>
                            </a>
                        </td>
                        <td>
                            <?php echo $user->email ?>
                        </td>
                        <td>
                            <?php echo $user->username ?>
                        </td>
                        <td class="text-right">
                            <a href="<?php echo $this->url('admin/user_edit', array('id' => $user->id)) ?>" class="btn btn-default btn-sm">
                                Edit
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>

        </table>

    </div>
</div>