<h1>Accounts</h1>

<div class="col-md-12 text-right">
    <a href="<?php echo $this->url('admin/account_add') ?>" class="btn btn-primary">Add</a>
</div>

<table class="table">
    <thead>
        <tr>
            <td>Account Name</td>
            <td>Subdomain</td>
            <td>&nbsp;</td>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->accounts as $account): ?>
            <tr>
                <td><a href="<?php echo $this->url('admin/account_view', ['id'=>$account->id]) ?>"><?php echo $account->name ?></a></td>
                <td><?php echo $account->subdomain ?></td>
                <td class="text-left">
                    <div class="btn-group">
                        <a type="button" class="btn btn-default" href="<?php echo $this->url('admin/account_schools', ['id'=>$account->id]) ?>">
                           View
                        </a>
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                            <span class="caret"></span>
                            <span class="sr-only">Toggle Dropdown</span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="<?php echo $this->url('admin/account_schools', ['id'=>$account->id]) ?>">Schools</a></li>
                            <li><a href="<?php echo $this->url('admin/account_teachers', ['id'=>$account->id]) ?>">Teachers</a></li>
                            <li><a href="<?php echo $this->url('admin/account_students', ['id'=>$account->id]) ?>">Students</a></li>
                        </ul>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>

</table>