<?php echo $this->partial('admin/accounts/partials/header.phtml', array('active' => 'schools', 'account' => $account)); ?>

<div class="row" style="padding-top: 12px">
    <div class="col-md-12 text-right">
        <a href="<?php echo $this->url('admin/school_add', array('id'=>$account->id)) ?>" class="btn btn-primary">Add School</a>
    </div>
</div>

<div class="row" style="padding-top: 12px">
    <div class="col-md-12">

        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($schools as $school): ?>
                    <tr>
                        <td>
                            <a href="<?php echo $this->url('admin/school_edit', array('a_id' => $account->id, 's_id' => $school->id)) ?>">
                                <?php echo $school->name ?>
                            </a>
                        </td>
                        <td class="">
                            <a href="<?php echo $this->url('admin/school_edit', array('a_id' => $account->id, 's_id' => $school->id)) ?>" class="btn btn-default btn-sm">
                                Edit
                            </a>

                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm">
                                    Actions
                                </button>
                                <button type="button" class="btn btn-default  btn-sm dropdown-toggle" data-toggle="dropdown">
                                    <span class="caret"></span>
                                    <span class="sr-only">Toggle Dropdown</span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="<?php echo $this->url('admin/upload_students', ['a_id'=>$account->id, 's_id' => $school->id]) ?>">Upload Students</a></li>
                                </ul>
                            </div>

                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>

        </table>

    </div>
</div>