<?php echo $this->partial('admin/accounts/partials/header.phtml', array('active' => 'students', 'account' => $account)); ?>

<div class="row" style="padding-top: 12px">
    <div class="col-md-12 text-right">
        <a href="<?php echo $this->url('admin/student_add', array('id'=>$account->id)) ?>" class="btn btn-primary">Add Student</a>
    </div>
</div>

<div class="row" style="padding-top: 12px">
    <div class="col-md-12">

        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($students as $student): ?>
                    <tr>
                        <td>
                            <a href="<?php echo $this->url('admin/student_edit', array('a_id' => $account->id, 's_id' => $student->id)) ?>">
                                <?php echo $student->firstName . ' ' . $student->lastName ?>
                            </a>
                        </td>
                        <td>
                            <?php echo $student->number ?>
                        </td>
                        <td class="text-right">
                            <a href="<?php echo $this->url('admin/student_edit', array('a_id' => $account->id, 's_id' => $student->id)) ?>" class="btn btn-default btn-sm">
                                Edit
                            </a>
                            <a href="<?php echo $this->url('admin/student_sequences', array('id' => $student->id)) ?>" class="btn btn-default btn-sm">
                                Sequences
                            </a>

                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>

        </table>

    </div>
</div>