<?php echo $this->partial('admin/accounts/partials/header.phtml', array('active' => 'teachers', 'account' => $account)); ?>

<div class="row" style="padding-top: 12px">
    <div class="col-md-12">

        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($schools as $school): ?>
                    <tr>
                        <td>
                            <a href="<?php echo $this->url('admin/school_edit', array('a_id' => $account->id, 's_id' => $school->id)) ?>">
                                <?php echo $school->name ?>
                            </a>
                        </td>
                        <td class="text-right">
                            <a href="<?php echo $this->url('admin/school_edit', array('a_id' => $account->id, 's_id' => $school->id)) ?>" class="btn btn-default btn-sm">
                                Edit
                            </a>

                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>

        </table>

    </div>
</div>