<div id="header">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                <img src="/img/logo.png" width="200" />
            </div>
            <div class="col-md-2">
                Step: <?php echo $container->currStep; ?>
            </div>
            <div class="col-md-6">
                <?php echo $container->getPercentComplete() . '%'; ?>
            </div>
        </div>
    </div>
</div>

    <?php
    /*
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s><ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>');

    echo $flash->render('error',   array('alert', 'alert-danger'));
    echo $flash->render('info',    array('alert', 'alert-info'));
    echo $flash->render('default', array('alert', 'alert-warning'));
    echo $flash->render('success', array('alert', 'alert-success'));
    */
    ?>


<div id="step_content">
    <iframe src="<?php echo $step->resource->url ?>" style="height: 100%; width: 100%"></iframe>
</div>


<div id="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2 text-right">
                <a href="/pathway/reset" class="btn btn-danger">Reset</a>
            </div>

            <div class="col-md-10 text-right">
                <?php if (!$container->isAtFirstStep()): ?>
                    <a href="<?php echo $this->url('mschool/pathway_previous'); ?>" class="btn btn-info">
                        <span class="glyphicon glyphicon-chevron-left"></span>Previous
                    </a>
                <?php endif; ?>
                <?php if ($container->isAtLastStep()): ?>
                    <a href="<?php echo $this->url('mschool/logout'); ?>" class="btn btn-primary">
                        Great job! Logout
                    </a>
                <?php else: ?>
                    <a href="<?php echo $this->url('mschool/pathway_next'); ?>" class="btn btn-success">
                        Next<span class="glyphicon glyphicon-chevron-right"></span>
                    </a>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>