<header>
    <nav class='navbar navbar-default navbar-fixed-top'>
        <?php /* STEPS */ ?>
        <div class="row">

            <div class="col-md-4">
                <span class="navbar-brand" href="<?php echo $this->url('mschool/home') ?>">mSchool</span>
            </div>

            <div class="col-md-6 sequence-header">
                    <?php for($i = 1; $i <= $container->numberOfSteps(); $i++): ?>
                        <input class="btn btn-sm <?php echo ($container->currStep == $i) ? ('btn-info') : ('btn-default') ?>" value="<?php echo $i ?>" type="button">
                    <?php endfor; ?>
            </div>

            <div class="col-md-2 sequence-header text-right">

                <?php if (!$container->isAtFirstStep()): ?>
<!--                    <a href="--><?php //echo $this->url('mschool/pathway_previous'); ?><!--" class="btn btn-sm btn-primary">-->
<!--                        <span class="glyphicon glyphicon-chevron-left"></span>Previous-->
<!--                    </a>-->
                <?php endif; ?>
                <?php if ($container->isAtLastStep()): ?>
                    <a href="<?php echo $this->url('mschool/pathway_finished'); ?>" class="btn btn-sm btn-primary">
                        Next
                    </a>
                <?php elseif ($step->isTimed()): ?>
                    <a href="<?php echo $this->url('mschool/pathway_next'); ?>" class="btn btn-sm btn-primary" id="pathway-next-btn" disabled>
                        <span id="pathway-next-text">Keep working!</span><span id="pathway-next-chevron" style="display: none" class="glyphicon glyphicon-chevron-right"></span>
                    </a>
                <?php else: ?>
                    <a href="<?php echo $this->url('mschool/pathway_next'); ?>" class="btn btn-sm btn-primary">
                        <span id="pathway-next-text">Next</span><span class="glyphicon glyphicon-chevron-right"></span>
                    </a>
                <?php endif; ?>

            </div>
        </div>

    </nav>
</header>
<div id='wrapper'>
    <section id='content' class="sequence-content">
        <div id="step_content">
            <iframe src="<?php echo $step->resource->url ?>" style="height: 100%; width: 100%"></iframe>
        </div>
    </section>
</div>

<?php /*
<div id="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2 text-right">
                <a href="/pathway/reset" class="btn btn-danger">Reset</a>
            </div>

            <div class="col-md-10 text-right">
                <?php if (!$container->isAtFirstStep()): ?>
                    <a href="<?php echo $this->url('mschool/pathway_previous'); ?>" class="btn btn-info">
                        <span class="glyphicon glyphicon-chevron-left"></span>Previous
                    </a>
                <?php endif; ?>
                <?php if ($container->isAtLastStep()): ?>
                    <a href="<?php echo $this->url('mschool/logout'); ?>" class="btn btn-primary">
                        Great job! Logout
                    </a>
                <?php elseif ($step->isTimed()): ?>
                    <a href="<?php echo $this->url('mschool/pathway_next'); ?>" class="btn btn-success" id="pathway-next-btn" disabled>
                        <span id="pathway-next-text">Keep working!</span><span id="pathway-next-chevron" style="display: none" class="glyphicon glyphicon-chevron-right"></span>
                    </a>
                <?php else: ?>
                    <a href="<?php echo $this->url('mschool/pathway_next'); ?>" class="btn btn-success">
                        <span id="pathway-next-text">Next</span><span class="glyphicon glyphicon-chevron-right"></span>
                    </a>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

*/