<h1>Steps</h1>

<div class="row" style="padding-top: 12px">
    <div class="col-md-12 text-right">
        <a href="<?php echo $this->url('admin/step_add') ?>" class="btn btn-primary">Add Step</a>
    </div>
</div>

<div class="row" style="padding-top: 12px">
    <div class="col-md-12">

        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Short Code</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($steps as $steps): ?>
                    <tr>
                        <td>
                            <a href="<?php echo $this->url('admin/step_edit', array('id' => $steps->id)) ?>">
                                <?php echo $steps->name ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $this->url('admin/step_edit', array('id' => $steps->id)) ?>">
                                <?php echo $steps->shortCode ?>
                            </a>
                        </td>
                        <td class="text-right">
                            <a href="<?php echo $this->url('admin/step_edit', array('id' => $steps->id)) ?>" class="btn btn-default btn-sm">
                                Edit
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>

        </table>

    </div>
</div>